name: generate_site

on:
  push
  #workflow_dispatch:       # allow running manually

jobs:
  generate_site:
    name : Generate Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script to populate site with articles
        run: python create_site.py
        shell: sh
      - name: Push changes back to repo
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
